import Data.Char(isLetter,toLower)
import Data.List(sort)
import Data.Map(Map,alter,elems,empty)

cities :: [String]
cities = [
    "Baghdad","Jerusalem","Tel Aviv","Amman","Beirut","Damascus","Tehran",
    "Mecca","Riyadh","Sana'a","Dubai","Istanbul","Kabul","Ankara","Haifa",
    "Suez","Muscat","Medina","Cairo","Homs","Aleppo","Mosul","Erbil","Kirkuk",
    "Falluja","Ramadi","Basrah","Mashhad","Abu Dhabi","Karbala"
    ]

countries :: [String]
countries = [
    "United Arab Emirates",
    "Nigeria",
    "Ghana",
    "Pitcairn Islands",
    "Ethiopia",
    "Algeria",
    "Niue",
    "Jordan",
    "Netherlands",
    "Andorra",
    "Turkey",
    "Madagascar",
    "Samoa",
    "Turkmenistan",
    "Eritrea",
    "Kazakhstan",
    "Paraguay",
    "Greece",
    "Cook Islands",
    "Iraq",
    "Azerbaijan",
    "Mali",
    "Brunei",
    "Thailand",
    "Central African Republic",
    "Gambia",
    "Saint Kitts and Nevis",
    "China",
    "Lebanon",
    "Serbia",
    "Belize",
    "Germany",
    "Switzerland",
    "Kyrgyzstan",
    "Guinea-Bissau",
    "Colombia",
    "Brazil",
    "Slovakia",
    "Republic of the Congo",
    "Barbados",
    "Belgium",
    "Romania",
    "Hungary",
    "Argentina",
    "Burundi",
    "Egypt",
    "Australia",
    "Venezuela",
    "Saint Lucia",
    "French Guiana",
    "United States Virgin Islands",
    "Moldova",
    "Turks and Caicos Islands",
    "Guinea",
    "Denmark",
    "Senegal",
    "Syria",
    "Bangladesh",
    "East Timor",
    "Djibouti",
    "Tanzania",
    "Qatar",
    "Isle of Man",
    "Ireland",
    "Tajikistan",
    "Tristan da Cunha",
    "Sahrawi Arab Democratic Republic",
    "Akrotiri and Dhekelia",
    "Christmas Island",
    "Sierra Leone",
    "Tuvalu",
    "Botswana",
    "Cayman Islands",
    "Ascension Island",
    "Guyana",
    "Gibraltar",
    "Guatemala",
    "Saint Barthélemy",
    "Guam",
    "Bermuda",
    "Easter Island",
    "Vietnam",
    "Zimbabwe",
    "Somaliland",
    "Cuba",
    "Finland",
    "Solomon Islands",
    "Pakistan",
    "Indonesia",
    "Saint Helena",
    "Israel",
    "South Sudan",
    "Afghanistan",
    "Uganda",
    "Nepal",
    "Sudan",
    "Ukraine",
    "Rwanda",
    "South Georgia and the South Sandwich Islands",
    "Jamaica",
    "Saint Vincent and the Grenadines",
    "Democratic Republic of the Congo",
    "Malaysia",
    "Kuwait",
    "Gabon",
    "Malawi",
    "Peru",
    "Portugal",
    "Slovenia",
    "Togo",
    "United Kingdom",
    "Angola",
    "Zambia",
    "Luxembourg",
    "Spain",
    "Marshall Islands",
    "Equatorial Guinea",
    "Maldives",
    "Nicaragua",
    "Bahrain",
    "Philippines",
    "Mozambique",
    "Saint Martin",
    "Lesotho",
    "Wallis and Futuna",
    "Swaziland",
    "Mexico",
    "Belarus",
    "Somalia",
    "Monaco",
    "Liberia",
    "Uruguay",
    "Comoros",
    "Russia",
    "Oman",
    "Kenya",
    "Bahamas",
    "Burma",
    "Chad",
    "India",
    "Palau",
    "Niger",
    "Cyprus",
    "Mauritania",
    "New Caledonia",
    "Tonga",
    "Greenland",
    "Aruba",
    "Norway",
    "Canada",
    "Burkina Faso",
    "American Samoa",
    "Federated States of Micronesia",
    "Panama",
    "French Polynesia",
    "Suriname",
    "France",
    "Sint Maarten",
    "Cambodia",
    "Montserrat",
    "Montenegro",
    "Mauritius",
    "Papua New Guinea",
    "Vanuatu",
    "Haiti",
    "Trinidad and Tobago",
    "Benin",
    "Czech Republic",
    "Cape Verde",
    "South Africa",
    "Kosovo",
    "North Korea",
    "Ecuador",
    "Morocco",
    "Iceland",
    "Latvia",
    "Saudi Arabia",
    "British Virgin Islands",
    "Italy",
    "Dominica",
    "Northern Mariana Islands",
    "Costa Rica",
    "Puerto Rico",
    "San Marino",
    "El Salvador",
    "Yemen",
    "Chile",
    "Dominican Republic",
    "São Tomé and Príncipe",
    "Bosnia and Herzegovina",
    "South Korea",
    "Singapore",
    "Macedonia",
    "Bulgaria",
    "Sri Lanka",
    "Grenada",
    "Jersey",
    "Antigua and Barbuda",
    "British Crown Dependency",
    "Saint Pierre and Miquelon",
    "Falkland Islands",
    "Nagorno-Karabakh Republic",
    "Sweden",
    "Bolivia",
    "Abkhazia",
    "Fiji",
    "Taiwan",
    "Estonia",
    "Kiribati",
    "Uzbekistan",
    "Georgia",
    "Honduras",
    "Iran",
    "Bhutan",
    "Albania",
    "Transnistria",
    "Japan",
    "Faroe Islands",
    "Libya",
    "South Ossetia",
    "Tunisia",
    "Mongolia",
    "Liechtenstein",
    "Malta",
    "Anguilla",
    "Vatican City",
    "Seychelles",
    "Austria",
    "Laos",
    "Lithuania",
    "Poland",
    "United States",
    "New Zealand",
    "Cocos (Keeling) Islands",
    "Curaçao",
    "Namibia",
    "Ivory Coast",
    "Cameroon",
    "Nauru",
    "Armenia",
    "Croatia",
    "Congo",
    "USA"
    ]

candidates :: [(String,(String,String))]
candidates =
    [((sort . map toLower . filter isLetter) (country ++ city),(country,city))|
     country <- countries, city <- cities,
     (length . filter isLetter) (country ++ city) == 12]

collected :: Map String [(String,String)]
collected =
    foldl (\ m (k,v) -> alter (Just . maybe [v] (v:)) k m) empty candidates

answers :: [[(String,String)]]
answers = filter ((> 1) . length) (elems  collected)

-- Iran/Abu Dhabi Bahrain/Dubai
