import Control.Monad(foldM_,when)
import Data.Char(isAlpha,toLower)
import Data.Map(Map,empty,insert,member,(!))

rm :: Int -> String -> [String]
rm n s
  | n <= 0 = [s]
  | length s < n = []
  | length s == n = [""]
  | otherwise = rm (n-1) (drop 1 s) ++ (map (take 1 s ++) (rm n (drop 1 s)))

search :: (Map String String,Map String String) -> String -> IO (Map String String,Map String String)
search (m1,m2) s = do
    let k = map toLower (filter isAlpha s)
    when (member k m1) (print (s,m1!k))
    mapM_ search1 (rm 3 k)
    return (foldl (flip (flip insert s)) m1 (rm 3 k),insert k s m2)
  where
    search1 k = when (member k m2) (print (s,m2!k))

main :: IO ()
main = foldM_ search (empty,empty) [
    "Abu Dhabi", "Abu Zabi",
    "Abuja",
    "Accra",
    "Addis Ababa", "Addis Abeba",
    "Algiers", "Dzayer", "Alger",
    "Amman", "Ammon",
    "Amsterdam",
    "Ankara", "Ancyra", "Angora", "Istanbul", "Constantinople",
    "Antananarivo", "Tananarive",
    "Ashgabat", "Ashkhabad", "Poltoratsk", "Asgabat",
    "Astana",
    "Asunción", "Asuncion",
    "Athens", "Athína", "Athina", "Athênai", "Athenai",
    "Baghdad",
    "Baku",
    "Bamako",
    "Bangkok", "Krung Thep Maha Nakhon", "Krung Thep",
    "Beijing", "Peking",
    "Beirut", "Bayrut", "Beyrut", "Beyrouth",
    "Belgrade", "Beograd",
    "Berlin",
    "Bogotá", "Bogota",
    "Brasília", "Brasilia",
    "Brazzaville",
    "Bucharest", "București", "Bucuresti",
    "Budapest",
    "Buenos Aires",
    "Cairo", "Kahire", "Al-Qāhirah", "Al-Qahirah",
    "Caracas",
    "Conakry",
    "Copenhagen", "København", "Kobenhavn", "Hafnia",
    "Dakar",
    "Damascus", "Dimashq",
    "Dhaka", "Dacca",
    "Doha",
    "Dublin", "Dubhlinn", "Dubhlind", "Duílinn",
    "Freetown",
    "Guatemala City", "Guatemala", "Guate",
    "Hanoi",
    "Harare", "Salisbury",
    "Hargeisa", "Hargeysa",
    "Havana", "La Habana",
    "Helsinki", "Helsingfors",
    "Hong Kong",
    "Islamabad", "Karachi",
    "Jakarta", "Djakarta",
    "Jerusalem", "Tel Aviv",
    "Kabul",
    "Kampala",
    "Kathmandu", "Katmandu", "Catmando", "Kantipur",
    "Khartoum",
    "Kiev", "Kyiv",
    "Kigali",
    "Kinshasa", "Léopoldville", "Leopoldville", "Leopoldstad",
    "Kuala Lumpur",
    "Lilongwe",
    "Lima", "Cusco", "Cuzco", "Qosqo",
    "Lisbon", "Qosqo",
    "Lomé", "Lome",
    "London",
    "Luanda", "Loanda",
    "Lusaka",
    "Madrid",
    "Managua",
    "Manila", "Maynilà", "Maynila",
    "Maputo", "Lourenço Marques", "Lourenco Marques",
    "Mexico City", "Ciudad de México", "Ciudad de Mexico",
    "Minsk",
    "Mogadishu", "Xamar", "Hamar",
    "Monrovia",
    "Montevideo",
    "Moscow", "Moskva", "Moscovia",
    "Muscat", "Masqaṭ", "Masqat", "Moscha",
    "Nairobi",
    "Naypyidaw", "Nay Pyi Taw", "Naypyitaw", "Kyetpyay", "Pyinmana", "Kyatpyay",
    "N'Djamena",
    "New Delhi", "Calcutta", "Kolkata",
    "Niamey",
    "Oslo", "Christiania", "Kristiania",
    "Ottawa",
    "Ouagadougou",
    "Panama City", "Ciudad de Panamá", "Ciudad de Panama", "Panama",
    "Paris",
    "Phnom Penh", "Krong Chaktomuk",
    "Port-au-Prince",
    "Prague", "Praha",
    "Pretoria", "Cape Town", "Kaapstad",
    "Pyongyang", "Kisong", "Hwangsong", "Rakrang", "Sŏgyong", "Sogyong", "Sodo,", "Hogyong", "Changan", "Heijō", "Heijo",
    "Quito",
    "Rabat",
    "Riyadh",
    "Rome", "Roma",
    "San José", "San Jose",
    "San Salvador",
    "Sana'a", "Sana", "Aden",
    "Santiago",
    "Santo Domingo",
    "Seoul",
    "Singapore",
    "Sofia", "Sofiya",
    "Sri Jayawardenepura Kotte", "Sri Jayewardenepura Kotte", "Colombo", "Kolamba",
    "Stockholm",
    "La Paz",
    "Taipei", "Taipei-fu", "Taihoku",
    "Tashkent", "Toshkent",
    "Tbilisi", "Tiflis",
    "Tegucigalpa",
    "Tehran",
    "Tokyo", "Tokio",
    "Tripoli",
    "Tunis",
    "Ulaanbaatar", "Ulan Bator",
    "Vienna", "Wein",
    "Warsaw", "Warszawa", "Warszewa", "Warszowa", "Worszewa", "Werszewa",
    "Washington, D.C.", "Washington",
    "Abidjan",
    "Yaoundé", "Yaounde",
    "Yerevan", "Erevan",
    "Zagreb", "Zagrab"
    ]

-- Djakarta Dakar
