import Data.List(sort)
import Data.Map(Map,empty,insert,member,(!))

search :: Map String String -> [String] -> [String]
search _ [] = []
search m (a:as)
  | length a < 6 || length a > 7 = search m as
  | member k m = (a++"/"++m!k) : search m as
  | otherwise = search (insert k a m) as
  where k = sort $ take 6 a

items :: [String]
items = [
  "tylenol", "anacin", "ritalin", "ozempic", "humira", "eliquis", "enbrel",
  "stelara", "rituxan", "avastin", "xarelto", "prevnar", "lyrica", "harvoni",
  "lantus", "sovaldi", "advair", "crestor", "nexium", "spiriva", "januvia",
  "epogen", "truvada", "diovan", "levemir", "gleevec", "glivec", "vyvanse",
  "namenda", "viagra", "incivo", "alimta", "victoza", "synagis", "avonex",
  "renvela", "cialis", "gilenya", "nasonex", "flovent", "flonase", "lovaza",
  "janumet", "procrit", "orencia", "humalog", "lunesta", "zytiga", "reyataz",
  "aciphex", "xolair", "lipitor", "benicar", "pradaxa", "vytorin", "tamiflu",
  "evista", "xeloda", "aranesp", "motrin", "bextra", "arcoxia", "repatha",
  "kymriah", "rogaine", "naropin", "relpax", "ceeoxx", "toradol", "zofran",
  "imitrex", "ultram", "zantac", "zoloft", "wildnil", "dsuvia", "sufenta",
  "tagamet", "zytanix", "mykrox", "midamor", "inderal", "valium", "discoid",
  "uremide", "nurofen", "brufen", "kenelog", "vagisil", "diuril", "posimir",
  "medrol", "librium", "orapred", "astonin", "diamox", "diacarb", "cortef",
  "epipen", "delysid", "ztlido", "aczone", "mebaral", "ametop", "dicaine",
  "analgin", "ergomar", "levoxyl", "thyrax", "luminal", "sezaby", "cevalin",
  "desoxyn", "orajel", "anbesol", "akovaz", "panadol", "noctec", "somnos",
  "somnote", "statex", "contin", "deracyn", "alprox", "restyl", "solanax",
  "neurol", "frontin", "lexotan", "lexatin", "bromam", "dormex", "albego",
  "risolid", "elenium", "levana", "frisium", "urbanol", "clozan", "cloxam",
  "sepazon", "olcadil", "dadumir", "antenex", "apaurin", "apzepam", "hexalid",
  "stedon", "prosom", "etizest", "pasaden", "victan", "meilax", "ronlax",
  "templex", "remnon", "dalmane", "restas", "paxipam", "alapryl", "havlane",
  "ativan", "orfidal", "lorenin", "temesta", "loramet", "nobrium", "ansilan",
  "mezapam", "rudotel", "raporan", "sedoxil", "versed", "erimin", "mogadon",
  "alodorm", "pacisyn", "dumolid", "stilny", "seresta", "serenid", "serepax",
  "sobril", "oxabenz", "oxapax", "opamox", "alepam", "medopam", "murelax",
  "noripam", "purata", "prazene", "centrax", "centrum", "temaze", "epsipam",
  "musaril", "halcion", "rilamir", "notison", "somese", "anexate", "lanexat",
  "mazicon", "sonata", "starnoc", "ambien", "nytamel", "sanval", "stilnox",
  "xolnox", "zoldem", "zolnod", "imovane", "rhovane", "ximovan", "zileze",
  "zopitan", "soluna", "tolvon", "remeron", "tecipul", "atravet", "acezine",
  "tindal", "repoise", "tyrylen", "cloxan", "truxal", "tercian", "dridol",
  "depixol", "prolixin", "haldol", "nosinan", "nozinan", "loxapac", "micefal",
  "taxilan", "sparine", "inofal", "artalan", "dartal", "dartan", "navane",
  "vesprin", "abilify", "saphris", "lonasen", "rexulti", "vraylar", "fanapt",
  "caplyta", "latuda", "buronil", "cremin", "zyprexa", "lanzek", "invega",
  "lullan", "roxiam", "serpasil", "eglonyl", "topral", "agreal", "agradil",
  "geodon", "zeldox", "arbidol", "tybost", "edurant", "olysio", "tyzeka",
  "valtrex", "valcyte", "relenza", "celexa", "effexor", "intuniv", "keppra",
  "prozac", "topamax", "clomid", "colcrys", "doxepin", "similac", "ensure",
  "ampyra", "inbrija", "cubicin", "ubrelvy", "exalgo", "viadur", "acuvue",
  "talvey", "terazol", "tremfya", "vermox", "prolene", "uptravy", "kineret",
  "prolia", "mimpara", "nplate", "evenity", "boniva", "otezla", "riabni",
  "iclusig", "aduhelm", "leqembi", "fampyra", "gazyva", "imraldi", "tysabri",
  "avalide", "avapro", "plavix", "byetta", "farxiga", "forxiga", "atripla",
  "azactam", "evotaz", "megace", "stustiva", "stocrin", "abecma", "droxia",
  "hydrea", "erbitux", "opdivo", "sprycel", "yervoy", "nulojix", "gemzar",
  "bilagol", "palfium", "reasec" , "clinium", "remivox", "imodium", "tinset",
  "rapifen", "nizoral", "livocab", "sirturo", "remynil", "neuvax", "perjeta",
  "kadcyla", "tarceva", "polivy", "esbriet", "actemra", "tnkase", "pegasys",
  "anaprox", "fuzeon", "kytril", "xenical", "zenapax", "cayston", "descovy",
  "emtriva", "epclusa", "genvoya", "hepsera", "macugen", "ranexa", "stribild",
  "veklury", "vemlidy", "viread", "vosevi", "yescarta", "zydelig", "zyrtec",
  "dorimax", "elmiron", "baxdela", "invanz", "mexsana", "fosamax", "avenova",
  "puregon", "hadlima", "norvast", "enovid", "allegra", "always", "charmin",
  "febreze", "pampers", "cascade", "tampax", "swiffer", "secret", "actonel",
  "activia", "clairol", "oxydol", "zaltrap", "kevzara", "libtayo", "inmazeb",
  "veopoz", "fusilev", "zevalin", "marqibo", "evomela", "abevmy", "kixelle",
  "semglee", "breyna", "altargo", "avamys", "avodart", "blenrep", "ceftin",
  "dectova", "duodart", "duvroq", "dyazide", "flolan", "fortum", "halfam",
  "imigran", "lacipil", "levitra", "mepron", "naramig", "nimbrex", "nucala",
  "ojjaara", "requip", "rythmol", "seroxat", "staxyn", "ultiva", "zeffix",
  "zejula", "zentel", "zinacef", "zinnat", "zovirax", "ambirix", "arexvy",
  "bexsero", "fendrix", "fluarix", "havrix", "hiberix", "kinrix", "menveo",
  "priorix", "rabipur", "rotarix", "twinrix", "amocaln", "prograf", "suprax",
  "subutex", "vetofol", "ziagen", "epivir", "rukobia", "tivicay", "lexiva",
  "telzir", "kivexa", "dovato", "juluca", "aurorix", "bactrim", "camleed",
  "cardene", "cathflo", "lariam", "librax", "madopar", "prolopa", "mircera",
  "ocrevus", "raptiva", "tasmar", "xofluza", "comtan", "exforge", "exjade",
  "famvir", "femara", "focalin", "foradil", "galvus", "ilaris", "jadenu",
  "kisqali", "jakavi", "jakafi", "kyriah", "lamisil", "lescol", "lotrel",
  "mayzent", "navoban", "odomzo", "neoral", "stalevo", "tasigna", "tekamlo",
  "rasilez", "tyzeca", "sebivo", "zometa", "zaditen", "denavir", "desenex",
  "maalox", "tavist", "tixylix", "yasmin", "nexavar", "zavesca", "veletri",
  "opsumit", "uptravi", "phonak", "unitron", "aklief", "benzac", "epiduo",
  "loceryl", "mirvaso", "oracea", "metvix", "alastin", "menopur", "menogon",
  "propess", "lutinus", "pentasa", "rebyota", "minurin", "testim", "venofer",
  "monjuvi", "ryzodeg", "novolin", "tresiba", "saxenda", "abreva", "skyrizi",
  "norvir", "rinvoq", "digoxin", "grazax", "ebastel", "tesavel", "efficib",
  "airtal", "cordran", "sativex", "monovo", "avestin", "stivant", "gralise",
  "cambia", "zipsor", "harnal", "xtandi", "flomax", "symoron", "veozah",
  "vibativ", "xospata", "lovenox", "dynabac", "sklice", "telfast", "colgate",
  "pfizer", "moderna", "janssen", "novavax", "bengay", "bandaid", "kleenex",
  "aveeno", "travivo", "tepezza", "tivdak", "aabstral", "pepcid", "mucinex",
  "woolite", "nyquil", "dayquil", "atamet", "icyhot", "visine", "oneaday",
  "rolaids", "trojan", "swanson", "sudafed", "lactaid", "enfamil", "cepacol",
  "zzzquil", "mylanta", "delsym", "abbott", "mederma", "systane", "lamisil",
  "biooil", "novartis", "abbvie", "prempro", "natrol", "hubble", "sanofi",
  "gilead", "avandia", "detrol", "alavert", "aricept", "aventis", "solesta",
  "ecotrin", "alevex", "altoids", "aquanet", "bactine", "beneful", "capsiva",
  "caress", "clorox", "clifbar", "dentyne", "depend", "duromed", "emetrol",
  "ennovea", "exederm", "garnier", "gerber", "huggies", "jergens", "miralax",
  "mrclean", "narcan", "nervive", "nexcare", "nioxin", "nuvomed", "nugenix",
  "noxzema", "norelco", "ogilvie", "pamprin", "pantene", "pledge", "playtex",
  "pinesol", "purell", "protec", "propel", "resolve", "renuzit", "revive",
  "revlon", "ricola", "splenda", "tictac", "vivarin", "zanfel", "zyrexin",
  ""
  ]

main :: IO ()
main = mapM_ putStrLn $ search empty items

-- best answer, but not sure about Clairol -> Ricola
